version: '3.8'

services:
  server:
    build: .
    networks:
      - legerNW
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - legerNW

  db:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - legerNW
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  legerNW:
