FROM node:21

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
