version: '3.8'

services:
  server:
    build: .
    networks:
      - legerNW
    depends_on:
      - db

  db:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=v${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - legerNW

networks:
  legerNW: